name: com.quizeee.quizeee
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pinput:
  fluttertoast:
  otp_count_down:
  image_picker:
  http: ^0.12.1
  provider: ^4.1.3
  dio:
  shimmer:
  localstorage: ^3.0.6
  intl:
  cached_network_image:
  flutter_countdown_timer:
  flutter_spinkit: ^4.1.2
  url_launcher:
  percent_indicator:
  onesignal_flutter: ^2.6.3
  webview_flutter:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/menubar.png
    - assets/images/flag.png
    - assets/images/logo.png
    - assets/images/poster.png
    - assets/images/pos1.png
    - assets/images/pos2.png
    - assets/images/home.png
    - assets/images/profile.png
    - assets/images/wallet.png
    - assets/images/create.png
    - assets/images/account.png
    - assets/images/notification.png
    - assets/images/cup.png
    - assets/images/hamburger.png
    - assets/images/home_fill.png
    - assets/images/account_fill.png
    - assets/images/wallet_fill.png
    - assets/images/create_fill.png
    - assets/images/cartoon.png
    - assets/images/rules.png
    - assets/images/stars.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:Bungee-Regular
  fonts:
    - family: MajorLeagueDuty
      fonts:
         - asset: assets/fonts/MajorLeagueDuty-LLYD.ttf

    - family: DebugFreeTrial
      fonts:
         - asset: assets/fonts/DebugFreeTrial-MVdYB.otf

    - family: RapierZero
      fonts:
         - asset: assets/fonts/RapierZero-325M.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
